name: CI
on:
  push:
    branches:
      - rawhide
  pull_request:
    branches:
      - rawhide

concurrency:
  group: ${ {github.event_name }}-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true 

jobs:
  CI:
    runs-on: ubuntu-24.04-arm
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build new image and Load it into Docker for testing
        uses: docker/build-push-action@v6
        with:
          tags: ArborX:latest
          file: Dockerfile
          pull: true
          push: false
          load: true
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Build and Test Kokkos using updated image
        run: |
          docker run -t --rm -v ${{ github.workspace }}/ArborX:/ArborX -w /ArborX ArborX:latest \
            sh -c \
              "fedpkg --name ArborX mockbuild"
