name: CI
on:
  push:
    branches:
      - rawhide
  pull_request:
    branches:
      - rawhide

concurrency:
  group: ${ {github.event_name }}-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true 

jobs:
  CI:
    runs-on: ubuntu-24.04-arm
    container:
      image: registry.fedoraproject.org/fedora:rawhide
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Build fedpg and friends
        run: dnf -y install wget fedpkg
      - name: Install Deps
        run:  dnf -y builddep ArborX.spec
      - name: Make SRPM
        run: |
          ./get_master.sh
          fedpkg srpm
      - name: Build rpm
        run: |
          module avail
          fedpkg local
