name: CI
on:
  push:
    branches:
      - rawhide
  pull_request:
    branches:
      - rawhide

concurrency:
  group: ${ {github.event_name }}-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true 

jobs:
  CI:
    runs-on: ubuntu-24.04-arm
    container:
      image: ghcr.io/kokkos/ci-containers/fedora:latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Build fedpg and friends
        run: sudo dnf -y install wget fedpkg Lmod
      - name: Install Deps
        run:  sudo dnf -y builddep ArborX.spec
      - name: Make SRPM
        run: |
          ./get_master.sh
          fedpkg srpm
      - name: Build rpm
        run: |
          . /etc/profile.d/modules.sh 
          module avail
          fedpkg local
